### ISSUE TITLE
Windows computer issue in Chrome - image region creation on Synapse

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/fishspy#9] opened 2017-08-23 01:09 UTC
On one Windows computer (in Chrome as well as in Firefox), the data management system will not allow a user to generate an image region (Zdu). The error that is given is just an unknown one that says talk to the system administrator.

**Comment by karlcz** [comment] 2017-09-01 19:04
Please reproduce the error and give me more complete info:

- what message(s) show in the browser
- what time exactly you encounter the error
- who was the logged in user when it happened

**Comment by BDemps** [comment] 2017-09-01 20:28
Error in browser (Google Chrome): "Error: Terminal Error: Unexpected error has occurred. Please report this to your system administrators." (and then it makes you click OK)
Time: 1:28pm on 9/1/2017
Zdu was the logged in user (on a windows computer)

**Comment by karlcz** [comment] 2017-09-05 18:04
@BDemps  there isn't any kind of link in the error page to show more details?

It's strange. I can't find any errors in the server log around Sep 1 13:28 other than basic stale session/login prompts.

We will probably do a new release of the server software soon, as part of adding study tracking for informatics-isi-edu/synspy#37 and that will also update Chaise, so I guess we might defer further investigation on this until the latest software is ready to test?

**Comment by BDemps** [comment] 2017-09-05 19:49
No, it just says yo contact administrators and makes us click ok. Want a
screenshot?

**Comment by karlcz** [comment] 2017-09-15 01:44
I think this was resolved as a policy issue for the user in question.  Since the older Chaise in use then had known issues with handling authorization failures, I am closing this.  If we see further GUI failures due to policy (and without a clear error message) we should fine new bugs.

**Closed as completed by karlcz** 2017-09-15 01:44 UTC

**Comment by BDemps** [comment] 2017-09-18 16:06
Yes, this is fine now. Thank you!

On Thu, Sep 14, 2017 at 6:44 PM, Karl Czajkowski <notifications@github.com>
wrote:

> I think this was resolved as a policy issue for the user in question.
> Since the older Chaise in use then had known issues with handling
> authorization failures, I am closing this. If we see further GUI failures
> due to policy (and without a clear error message) we should fine new bugs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_fishspy_issues_9-23issuecomment-2D329654542&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=3MvPD_58G8yRf7zOlv74g019AvfrYw2ftayIxQEAtq8&s=xi1wfzajLZfHxGQDK1nHbvh1aWUVnZEyrmHpk_WTDf8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt4n-5FnjHsHlOsnaFMrS1l80Y7NMGAks5sidaHgaJpZM4O-5FXfB&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=3MvPD_58G8yRf7zOlv74g019AvfrYw2ftayIxQEAtq8&s=k1ECiuRxgqm09TgeuO5BgDx2ub9Ogkpc2UKDuUch0DM&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818
